//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cortina
    {
        public int Id { get; set; }
        public string Ubicacion { get; set; }
        public double Ancho { get; set; }
        public double Alto { get; set; }
        public string Tela { get; set; }
        public string Posicion { get; set; }
        public double MetrosCuadrados { get; set; }
        public int Valor { get; set; }
        public int ClienteCodigo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
